/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Zen Apricorna (https://sketchfab.com/zenartdesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-neon-city-sketch-9b6c4c2c58b14d59a0adde635b7f9762
Title: Futuristic Neon City Sketch
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

const HackerRoom = (props) => {
  const { nodes, materials } = useGLTF(
    "/models/futuristic_neon_city_sketch/scene.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.material_0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.material_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.material_2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.material_3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.material_4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.material_5}
      />
    </group>
  );
}



useGLTF.preload("/models/futuristic_neon_city_sketch/scene.gltf");

export default HackerRoom;

